/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PublicRegisterRouteImport } from './routes/_public/register'
import { Route as PublicLoginRouteImport } from './routes/_public/login'
import { Route as AuthenticatedForbiddenRouteImport } from './routes/_authenticated/forbidden'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedChildrenRouteImport } from './routes/_authenticated/children'
import { Route as AuthenticatedAuditRouteImport } from './routes/_authenticated/audit'
import { Route as AuthenticatedAccessAuditRouteImport } from './routes/_authenticated/access-audit'
import { Route as AuthenticatedZonesIndexRouteImport } from './routes/_authenticated/zones.index'
import { Route as AuthenticatedZonesCreateRouteImport } from './routes/_authenticated/zones.create'
import { Route as AuthenticatedZonesIdRouteImport } from './routes/_authenticated/zones.$id'
import { Route as AuthenticatedZonesIdEditRouteImport } from './routes/_authenticated/zones.$id.edit'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRegisterRoute = PublicRegisterRouteImport.update({
  id: '/_public/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicLoginRoute = PublicLoginRouteImport.update({
  id: '/_public/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedForbiddenRoute = AuthenticatedForbiddenRouteImport.update({
  id: '/forbidden',
  path: '/forbidden',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChildrenRoute = AuthenticatedChildrenRouteImport.update({
  id: '/children',
  path: '/children',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAuditRoute = AuthenticatedAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAccessAuditRoute =
  AuthenticatedAccessAuditRouteImport.update({
    id: '/access-audit',
    path: '/access-audit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedZonesIndexRoute = AuthenticatedZonesIndexRouteImport.update({
  id: '/zones/',
  path: '/zones/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedZonesCreateRoute =
  AuthenticatedZonesCreateRouteImport.update({
    id: '/zones/create',
    path: '/zones/create',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedZonesIdRoute = AuthenticatedZonesIdRouteImport.update({
  id: '/zones/$id',
  path: '/zones/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedZonesIdEditRoute =
  AuthenticatedZonesIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthenticatedZonesIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/access-audit': typeof AuthenticatedAccessAuditRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/children': typeof AuthenticatedChildrenRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/forbidden': typeof AuthenticatedForbiddenRoute
  '/login': typeof PublicLoginRoute
  '/register': typeof PublicRegisterRoute
  '/zones/$id': typeof AuthenticatedZonesIdRouteWithChildren
  '/zones/create': typeof AuthenticatedZonesCreateRoute
  '/zones/': typeof AuthenticatedZonesIndexRoute
  '/zones/$id/edit': typeof AuthenticatedZonesIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/access-audit': typeof AuthenticatedAccessAuditRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/children': typeof AuthenticatedChildrenRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/forbidden': typeof AuthenticatedForbiddenRoute
  '/login': typeof PublicLoginRoute
  '/register': typeof PublicRegisterRoute
  '/zones/$id': typeof AuthenticatedZonesIdRouteWithChildren
  '/zones/create': typeof AuthenticatedZonesCreateRoute
  '/zones': typeof AuthenticatedZonesIndexRoute
  '/zones/$id/edit': typeof AuthenticatedZonesIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/access-audit': typeof AuthenticatedAccessAuditRoute
  '/_authenticated/audit': typeof AuthenticatedAuditRoute
  '/_authenticated/children': typeof AuthenticatedChildrenRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/forbidden': typeof AuthenticatedForbiddenRoute
  '/_public/login': typeof PublicLoginRoute
  '/_public/register': typeof PublicRegisterRoute
  '/_authenticated/zones/$id': typeof AuthenticatedZonesIdRouteWithChildren
  '/_authenticated/zones/create': typeof AuthenticatedZonesCreateRoute
  '/_authenticated/zones/': typeof AuthenticatedZonesIndexRoute
  '/_authenticated/zones/$id/edit': typeof AuthenticatedZonesIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/access-audit'
    | '/audit'
    | '/children'
    | '/dashboard'
    | '/forbidden'
    | '/login'
    | '/register'
    | '/zones/$id'
    | '/zones/create'
    | '/zones/'
    | '/zones/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/access-audit'
    | '/audit'
    | '/children'
    | '/dashboard'
    | '/forbidden'
    | '/login'
    | '/register'
    | '/zones/$id'
    | '/zones/create'
    | '/zones'
    | '/zones/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/access-audit'
    | '/_authenticated/audit'
    | '/_authenticated/children'
    | '/_authenticated/dashboard'
    | '/_authenticated/forbidden'
    | '/_public/login'
    | '/_public/register'
    | '/_authenticated/zones/$id'
    | '/_authenticated/zones/create'
    | '/_authenticated/zones/'
    | '/_authenticated/zones/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  PublicLoginRoute: typeof PublicLoginRoute
  PublicRegisterRoute: typeof PublicRegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/register': {
      id: '/_public/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof PublicRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/login': {
      id: '/_public/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PublicLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/forbidden': {
      id: '/_authenticated/forbidden'
      path: '/forbidden'
      fullPath: '/forbidden'
      preLoaderRoute: typeof AuthenticatedForbiddenRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/children': {
      id: '/_authenticated/children'
      path: '/children'
      fullPath: '/children'
      preLoaderRoute: typeof AuthenticatedChildrenRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/audit': {
      id: '/_authenticated/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuthenticatedAuditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/access-audit': {
      id: '/_authenticated/access-audit'
      path: '/access-audit'
      fullPath: '/access-audit'
      preLoaderRoute: typeof AuthenticatedAccessAuditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/zones/': {
      id: '/_authenticated/zones/'
      path: '/zones'
      fullPath: '/zones/'
      preLoaderRoute: typeof AuthenticatedZonesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/zones/create': {
      id: '/_authenticated/zones/create'
      path: '/zones/create'
      fullPath: '/zones/create'
      preLoaderRoute: typeof AuthenticatedZonesCreateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/zones/$id': {
      id: '/_authenticated/zones/$id'
      path: '/zones/$id'
      fullPath: '/zones/$id'
      preLoaderRoute: typeof AuthenticatedZonesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/zones/$id/edit': {
      id: '/_authenticated/zones/$id/edit'
      path: '/edit'
      fullPath: '/zones/$id/edit'
      preLoaderRoute: typeof AuthenticatedZonesIdEditRouteImport
      parentRoute: typeof AuthenticatedZonesIdRoute
    }
  }
}

interface AuthenticatedZonesIdRouteChildren {
  AuthenticatedZonesIdEditRoute: typeof AuthenticatedZonesIdEditRoute
}

const AuthenticatedZonesIdRouteChildren: AuthenticatedZonesIdRouteChildren = {
  AuthenticatedZonesIdEditRoute: AuthenticatedZonesIdEditRoute,
}

const AuthenticatedZonesIdRouteWithChildren =
  AuthenticatedZonesIdRoute._addFileChildren(AuthenticatedZonesIdRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccessAuditRoute: typeof AuthenticatedAccessAuditRoute
  AuthenticatedAuditRoute: typeof AuthenticatedAuditRoute
  AuthenticatedChildrenRoute: typeof AuthenticatedChildrenRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedForbiddenRoute: typeof AuthenticatedForbiddenRoute
  AuthenticatedZonesIdRoute: typeof AuthenticatedZonesIdRouteWithChildren
  AuthenticatedZonesCreateRoute: typeof AuthenticatedZonesCreateRoute
  AuthenticatedZonesIndexRoute: typeof AuthenticatedZonesIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccessAuditRoute: AuthenticatedAccessAuditRoute,
  AuthenticatedAuditRoute: AuthenticatedAuditRoute,
  AuthenticatedChildrenRoute: AuthenticatedChildrenRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedForbiddenRoute: AuthenticatedForbiddenRoute,
  AuthenticatedZonesIdRoute: AuthenticatedZonesIdRouteWithChildren,
  AuthenticatedZonesCreateRoute: AuthenticatedZonesCreateRoute,
  AuthenticatedZonesIndexRoute: AuthenticatedZonesIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  PublicLoginRoute: PublicLoginRoute,
  PublicRegisterRoute: PublicRegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
